version: '3.8'
services:
  # nginx
  chat-vue-nginx:
    container_name: nginx-container
    image: nginx:stable-alpine
    ports:
      - "8077:80"
    volumes:
      - ./chat_app:/var/www/chat_vue
      - ./_docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - chat-vue-php_8
      - chat-vue-mariadb
    networks:
      - chat-vue

  #php
  chat-vue-php_8:
    container_name: php-8-container
    build:
      context: .
      dockerfile: ./_docker/php/php.dockerfile
    entrypoint: /var/www/_docker/php/entrypoint.sh
    volumes:
      - ./chat_app/:/var/www/chat_vue
      - ./_docker/php/php.ini:/usr/local/etc/php/php.ini
#      - ./_docker/php/entrypoint.sh:/var/www/chat-vue.local/entrypoint.sh
    command: php-fpm
    depends_on:
      - chat-vue-mariadb
    ports:
#      - "9000:9000"
      - "8088:8088"
    networks:
      - chat-vue

  # node js
  chat-vue-nodejs:
    container_name: nodejs
    build:
      context: .
      dockerfile: ./_docker/nodejs/nodejs.dockerfile
    restart: unless-stopped
    entrypoint: /var/www/_docker/nodejs/entrypoint.sh
    volumes:
      - ./chat_socket_server:/var/www/chat_socket_server
#      - ./_docker/nodejs/entrypoint.sh:/var/www/chat-vue.local/entrypoint.sh
    ports:
      - "3077:3077"
    depends_on:
      - chat-vue-php_8
    networks:
      - chat-vue

  #mysql
  chat-vue-mariadb:
    container_name: mariadb-container
    image: mariadb:10.1.14
    ports:
      - "4306:3306"
    volumes:
      - ./_docker/mysql:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: always
    environment:
      MYSQL_DATABASE: chat_vue
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
    networks:
      - chat-vue

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - chat-vue-mariadb:db
    restart: always
    ports:
      - "8084:80"
    environment:
      - PMA_ARBITRARY=1
    networks:
      - chat-vue

networks:
  chat-vue:
    driver: bridge
